package com.media.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.media.model.base.BaseCityClass;

/**
 * Generated by JFinal.
 * CityClass model.
 */

@SuppressWarnings("serial")
public class CityClass extends BaseCityClass<CityClass> {

	public static final CityClass me = new CityClass();
	

//	查询，全部城市	
	public List<CityClass> cityListAll(String provinceId) {
		return find("select * from tb_city_class where provinceId="+provinceId+" order by cityId asc");
	}
		
//	查询，分页，城市，传入的cityId为限定条件		
	public Page<CityClass> cityList(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from tb_city_class order by cityId asc");
	}

	//根据城市名寻找城市ID
	public int findCityId(String city) {
		return findFirst("select cityId from tb_city_class where cityName='"+city+"'").get("cityId");
	}
	
	//根据城市ID寻找城市名
	public String findCityName(int cityId) {
		return findFirst("select cityName from tb_city_class where cityId='"+cityId+"'").getStr("cityName");
	}
	
//	查询，分页，自媒体，传入的cityName为限定条件
	public Page<CityClass> mediaCityList(int pageNumber, int pageSize, String cityName) {
		return paginate(pageNumber, pageSize, "select *", "from tb_media_info where cityName='"+cityName+"' order by mediaId asc");
	}
	
	public Page<CityClass> hotCityIdList() {
		return paginate(1,6,"select cityId", "from tb_city_class order by citySearchNum desc");
	}
	
	public List hotCityList(int cityId) {
		return find("select cityId,cityName,cityMediaNum,citySearchNum,provinceName"
				+ " from tb_city_class,tb_province_class where tb_city_class.provinceId = tb_province_class.provinceId and"
				+ " cityId = '"+cityId+"'");
	}

}
