package com.media.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.media.model.base.BaseMainMediaClass;

/**
 * Generated by JFinal.
 * MainMediaClass model.
 */

@SuppressWarnings("serial")
public class MainMediaClass extends BaseMainMediaClass<MainMediaClass> {

	public static final MainMediaClass me = new MainMediaClass();

//	查询，全部主分类	
	public List<MainMediaClass> mainMediaClassListAll() {
		return find("select * from tb_main_media_class order by mainTypesId asc");
	}
	
//	查询，分页，全部主分类
	public Page<MainMediaClass> mainMediaClassList(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from tb_main_media_class order by mainTypesId asc");
	}
	
}
