package com.media.model;

import com.jfinal.plugin.activerecord.Page;
import com.media.model.base.BaseMinorMediaClass;

/**
 * Generated by JFinal.
 * MinorMediaClass model.
 */

@SuppressWarnings("serial")
public class MinorMediaClass extends BaseMinorMediaClass<MinorMediaClass> {
	
	public static final MinorMediaClass me = new MinorMediaClass();

//	查询，分页，全部次分类
	public Page<MinorMediaClass> minorMediaClassListAll(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from tb_minor_media_class order by minorTypeId asc");
	}
	
//	查询测试，分页，次分类，mainTypesId=2，
//	public Page<MinorMediaClass> minorMediaClassList(int pageNumber, int pageSize) {
//		return paginate(pageNumber, pageSize, "select *", "from tb_minor_media_class where mainTypesId= "+"2"+" order by minorTypeId asc");
//	}

//	查询，分页，次分类，传入的mainTypesId为限定条件
	public Page<MinorMediaClass> minorMediaClassList(int pageNumber, int pageSize, String mainTypesId) {
		return paginate(pageNumber, pageSize, "select *", "from tb_minor_media_class where mainTypesId= "+mainTypesId+" order by minorTypeId asc");
	}
}
