package com.media.config.mapping;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.media.model.CityClass;
import com.media.model.CollectMedia;
import com.media.model.CollectUser;
import com.media.model.FansNum;
import com.media.model.FeedBack;
import com.media.model.IndentInfo;
import com.media.model.MainMediaClass;
import com.media.model.MediaInfo;
import com.media.model.MinorMediaClass;
import com.media.model.NewsClass;
import com.media.model.ProvinceClass;
import com.media.model.ReportMedia;
import com.media.model.ReportUser;
import com.media.model.SchoolClass;
import com.media.model.SortClass;
import com.media.model.UserInfo;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	public static void mapping(ActiveRecordPlugin arp) {
		
		arp.addMapping("tb_indent_information", "indentId", IndentInfo.class);
		arp.addMapping("tb_media_info", "mediaId", MediaInfo.class);
		arp.addMapping("tb_school_class", "schoolId", SchoolClass.class);
		arp.addMapping("tb_province_class", "provinceId", ProvinceClass.class);
		arp.addMapping("tb_city_class", "cityId", CityClass.class);
		arp.addMapping("tb_sort_class", "sortId", SortClass.class);
		arp.addMapping("tb_collect_user", "collectId", CollectUser.class);
		arp.addMapping("tb_collect_media", "collectId", CollectMedia.class);
		arp.addMapping("tb_user_info", "userId", UserInfo.class);
		arp.addMapping("tb_news_class", "newsId", NewsClass.class);
		arp.addMapping("tb_user_feedback", "feedId", FeedBack.class);
		arp.addMapping("tb_report_media", "reportId", ReportMedia.class);
		arp.addMapping("tb_report_user", "reportId", ReportUser.class);
		arp.addMapping("tb_fansnum_class", "fansNumId", FansNum.class);
	//	arp.addMapping("tb_main_media_class", "mainTypesId", MainMediaClass.class);
	//	arp.addMapping("tb_minor_media_class", "minorTypeId", MinorMediaClass.class);
		
	}
}
