package com.media.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */

@SuppressWarnings("serial")
public abstract class BaseMediaInfo<M extends BaseMediaInfo<M>> extends Model<M> implements IBean {
	
	public void setMediaId(java.lang.Integer mediaId) {
		set("mediaId", mediaId);
	}

	public java.lang.Integer getMediaId() {
		return get("mediaId");
	}
	
	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}
	
	public void setIsOpen(java.lang.Integer isOpen) {
		set("isOpen", isOpen);
	}

	public java.lang.Integer getIsOpen() {
		return get("isOpen");
	}
	
	public void setIsVerification(java.lang.Integer isVerification) {
		set("isVerification", isVerification);
	}

	public java.lang.Integer getIsVerification() {
		return get("isVerification");
	}	

	public void setMediaName(java.lang.String mediaName) {
		set("mediaName", mediaName);
	}

	public java.lang.String getMediaName() {
		return get("mediaName");
	}
	
	public void setWechatNum(java.lang.String wechatNum) {
		set("wechatNum", wechatNum);
	}

	public java.lang.String getWechatNum() {
		return get("wechatNum");
	}	

	public void setWechatHead(java.lang.String wechatHead) {
		set("wechatHead", wechatHead);
	}

	public java.lang.String getWechatHead() {
		return get("wechatHead");
	}
	
	public void setTwoCode(java.lang.String twoCode) {
		set("twoCode", twoCode);
	}

	public java.lang.String getTwoCode() {
		return get("twoCode");
	}
	
	public void setFansNum(java.lang.Integer fansNum) {
		set("fansNum", fansNum);
	}

	public java.lang.Integer getFansNum() {
		return get("fansNum");
	}
	
	public void setReadNum(java.lang.Integer readNum) {
		set("readNum", readNum);
	}

	public java.lang.Integer getReadNum() {
		return get("readNum");
	}
	
	public void setIntro(java.lang.String intro) {
		set("intro", intro);
	}

	public java.lang.String getIntro() {
		return get("intro");
	}
	
	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("provinceId");
	}
	
	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}
	
	public void setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("schoolId");
	}	
	
	public void setSoftMoreFirPrice(java.lang.Integer softMoreFirPrice) {
		set("softMoreFirPrice", softMoreFirPrice);
	}

	public java.lang.Integer getSoftMoreFirPrice() {
		return get("softMoreFirPrice");
	}
	
	public void setSoftMoreSecPrice(java.lang.Integer softMoreSecPrice) {
		set("softMoreSecPrice", softMoreSecPrice);
	}

	public java.lang.Integer getSoftMoreSecPrice() {
		return get("softMoreSecPrice");
	}
	
	public void setSoftMoreOtherPrice(java.lang.Integer softMoreOtherPrice) {
		set("softMoreOtherPrice", softMoreOtherPrice);
	}

	public java.lang.Integer getSoftMoreOtherPrice() {
		return get("softMoreOtherPrice");
	}
	
	public void setSoftSimplePrice(java.lang.Integer softSimplePrice) {
		set("softSimplePrice", softSimplePrice);
	}

	public java.lang.Integer getSoftSimplePrice() {
		return get("softSimplePrice");
	}
	
	public void setHardMoreFirPrice(java.lang.Integer hardMoreFirPrice) {
		set("hardMoreFirPrice", hardMoreFirPrice);
	}

	public java.lang.Integer getHardMoreFirPrice() {
		return get("hardMoreFirPrice");
	}
	
	public void setHardMoreSecPrice(java.lang.Integer hardMoreSecPrice) {
		set("hardMoreSecPrice", hardMoreSecPrice);
	}

	public java.lang.Integer getHardMoreSecPrice() {
		return get("hardMoreSecPrice");
	}
	
	public void setHardMoreOtherPrice(java.lang.Integer hardMoreOtherPrice) {
		set("hardMoreOtherPrice", hardMoreOtherPrice);
	}

	public java.lang.Integer getHardMoreOtherPrice() {
		return get("hardMoreOtherPrice");
	}

	public void setHardSimplePrice(java.lang.Integer hardSimplePrice) {
		set("hardSimplePrice", hardSimplePrice);
	}

	public java.lang.Integer getHardSimplePrice() {
		return get("hardSimplePrice");
	}
	
	public void setMedTypesFir(java.lang.Integer medTypesFir) {
		set("medTypesFir", medTypesFir);
	}

	public java.lang.Integer getMedTypesFir() {
		return get("medTypesFir");
	}
	
	public void setMedTypesSec(java.lang.Integer medTypesSec) {
		set("medTypesSec", medTypesSec);
	}

	public java.lang.Integer getMedTypesSec() {
		return get("medTypesFir");
	}	

	public void setMedTypesThird(java.lang.Integer medTypesThird) {
		set("medTypesThird", medTypesThird);
	}

	public java.lang.Integer getMedTypesThird() {
		return get("medTypesThird");
	}	
	
	public void setIndentNum(java.lang.Integer indentNum) {
		set("indentNum", indentNum);
	}
	public java.lang.Integer getIndentNum() {
		return get("indentNum");
	}
	
	public void setCollectNum(java.lang.Integer collectNum) {
		set("collectNum", collectNum);
	}
	public java.lang.Integer getCollectNum() {
		return get("collectNum");
	}
}
