package com.media.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */

@SuppressWarnings("serial")
public abstract class BaseProvinceClass<M extends BaseProvinceClass<M>> extends Model<M> implements IBean {
	
	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}
	public java.lang.Integer getProvinceId(){
		return get("provinceId");
	}
	
	public void setProvinceName(java.lang.String provinceName){
		set("provinceName", provinceName);
	}
	
	public java.lang.String getProvinceName() {
		return get("provinceName");
	}
}
