package com.media.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */

@SuppressWarnings("serial")
public abstract class BaseMinorMediaClass<M extends BaseMinorMediaClass<M>> extends Model<M> implements IBean {

	public void setMinorTypeId(java.lang.Integer minorTypeId) {
		set("minorTypeId", minorTypeId);
	}

	public java.lang.Integer getMinorTypeId() {
		return get("minorTypeId");
	}
	
	public void setMainTypesId(java.lang.Integer mainTypesId) {
		set("mainTypesId", mainTypesId);
	}

	public java.lang.Integer getMainTypesId() {
		return get("mainTypesId");
	}

	public void setMinorTypesName(java.lang.String minorTypesName) {
		set("title", minorTypesName);
	}

	public java.lang.String getMinorTypesName() {
		return get("minorTypesName");
	}
}
