package com.media.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */

@SuppressWarnings("serial")
public abstract class BaseCityClass<M extends BaseCityClass<M>> extends Model<M> implements IBean {
	
	
	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}
	
	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("provinceId");
	}
	
	public void setCityName(java.lang.String cityName) {
		set("cityName", cityName);
	}

	public java.lang.String getCityName() {
		return get("cityName");
	}
	
	public void setCitySearchNum(java.lang.Integer citySearchNum) {
		set("citySearchNum", citySearchNum);
	}

	public java.lang.Integer getCitySearchNum() {
		return get("citySearchNum");
	}
	
	public void setCityMediaNum(java.lang.Integer cityMediaNum) {
		set("cityMediaNum", cityMediaNum);
	}

	public java.lang.Integer getCityMediaNum() {
		return get("cityMediaNum");
	}
	
}
