package com.media.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMainMediaClass<M extends BaseMainMediaClass<M>> extends Model<M> implements IBean {
	
	public void setMainTypesId(java.lang.Integer mainTypesId) {
		set("mainTypesId", mainTypesId);
	}

	public java.lang.Integer getMainTypesId() {
		return get("mainTypesId");
	}

	public void setMainTypesName(java.lang.String mainTypesName) {
		set("mainTypesName", mainTypesName);
	}

	public java.lang.String getMainTypesName() {
		return get("mainTypesName");
	}
}
